# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crossml.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='crossml.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rcrossml.proto\"\xaa\x02\n\x11\x43rossoutMLSetting\x12\x14\n\x0c\x64isplayIndex\x18\x01 \x01(\x05\x12\x10\n\x08\x66ullAuto\x18\x02 \x01(\x08\x12\x0e\n\x06shiftX\x18\x03 \x01(\x05\x12\x0e\n\x06shiftY\x18\x04 \x01(\x05\x12\x13\n\x0b\x63\x61rMaxSpeed\x18\x05 \x01(\x05\x12\x1c\n\x14\x63\x65nterDetectDistance\x18\x06 \x01(\x05\x12\x18\n\x10lrDetectDistance\x18\x07 \x01(\x05\x12\x19\n\x11\x66rontDetectDegree\x18\x08 \x01(\x05\x12\x18\n\x10targetDisplayFPS\x18\t \x01(\x05\x12\x14\n\x0c\x64\x65tectionFPS\x18\n \x01(\x05\x12\x17\n\x0fshowDebugWindow\x18\x0b \x01(\x08\x12\x1c\n\x14\x63heckStuckFrameCount\x18\x0c \x01(\x05\x62\x06proto3'
)




_CROSSOUTMLSETTING = _descriptor.Descriptor(
  name='CrossoutMLSetting',
  full_name='CrossoutMLSetting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='displayIndex', full_name='CrossoutMLSetting.displayIndex', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fullAuto', full_name='CrossoutMLSetting.fullAuto', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shiftX', full_name='CrossoutMLSetting.shiftX', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shiftY', full_name='CrossoutMLSetting.shiftY', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='carMaxSpeed', full_name='CrossoutMLSetting.carMaxSpeed', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='centerDetectDistance', full_name='CrossoutMLSetting.centerDetectDistance', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lrDetectDistance', full_name='CrossoutMLSetting.lrDetectDistance', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frontDetectDegree', full_name='CrossoutMLSetting.frontDetectDegree', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='targetDisplayFPS', full_name='CrossoutMLSetting.targetDisplayFPS', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detectionFPS', full_name='CrossoutMLSetting.detectionFPS', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='showDebugWindow', full_name='CrossoutMLSetting.showDebugWindow', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='checkStuckFrameCount', full_name='CrossoutMLSetting.checkStuckFrameCount', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=316,
)

DESCRIPTOR.message_types_by_name['CrossoutMLSetting'] = _CROSSOUTMLSETTING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CrossoutMLSetting = _reflection.GeneratedProtocolMessageType('CrossoutMLSetting', (_message.Message,), {
  'DESCRIPTOR' : _CROSSOUTMLSETTING,
  '__module__' : 'crossml_pb2'
  # @@protoc_insertion_point(class_scope:CrossoutMLSetting)
  })
_sym_db.RegisterMessage(CrossoutMLSetting)


# @@protoc_insertion_point(module_scope)
